### ISSUE TITLE
Link with a child of integer 0 returns returns the href

### ISSUE THREAD

**Issue by dasturias** [dbudwin/react-secure-link#11]
If I have something like:
```
<SecureLink href={url}>{0}</SecureLink>
```
It should have a link with 0 as the clickable link. This would be the behavior if I had something like 
```
<a href={url}>{0}</a>
```

Looking at the code it because you check the boolean of the children. However this check should probably be for just null, undefined, and empty string.

**Comment by dbudwin** [comment]
Thanks for the notification, I'll look into it!

**Comment by dbudwin** [comment]
@dasturias I have reproduced and fixed the bug locally...I'm going to make some other tweaks surrounding this code as well and add more tests around it.  I will likely get the PR up in 1 or 2 days and will update you when I do!

Thanks for the bug report!

**Comment by dbudwin** [comment]
@dasturias This issue should be resolved.  Once again, thanks for bringing it to my attention.  Let me know if you have any further issues!

**Comment by dasturias** [comment]
Thanks reviewed the PR and it looks good! I'll update to the latest. Super thanks for the super fast fix!
